apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
- name: mutating-webhook.default.svc
  matchPolicy: Equivalent
  admissionReviewVersions: ["v1"]
  sideEffects: None
  rules:
  - operations: ["CREATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    scope: "Namespaced"
  failurePolicy: Ignore
  timeoutSeconds: 20
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3ekNDQXRlZ0F3SUJBZ0lVQVdPMFdISDVzb1h0SGxiUjJZcUlrY1VMaTVjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURVpNQmNHQTFVRUF3d1FiWFYwWVhScGJtY3RkMlZpYUc5dmF6RUxNQWtHQTFVRUJoTUNUVXN4RWpBUQpCZ05WQkFnTUNVMWhZMlZrYjI1cFlURVBNQTBHQTFVRUJ3d0dVMnR2Y0dwbE1SSXdFQVlEVlFRS0RBbHJiV2wwClpYWnphMmt3SGhjTk1qSXhNREUyTVRBek1UVTVXaGNOTWpjeE1ERTFNVEF6TVRVNVdqQmhNUmt3RndZRFZRUUQKREJCdGRYUmhkR2x1WnkxM1pXSm9iMjlyTVFzd0NRWURWUVFHRXdKTlN6RVNNQkFHQTFVRUNBd0pUV0ZqWldSdgpibWxoTVE4d0RRWURWUVFIREFaVGEyOXdhbVV4RWpBUUJnTlZCQW9NQ1d0dGFYUmxkbk5yYVRDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1wb0xIMlZZWXk0SUZ3bGtHWG1OVktpUFFnaVJEdUoKNm1obnVuTUltU1NxRTJrSDdGN2xhazdQTzdSM0xTMXk2Y2djY0c4Z1FBUmQ2bEZaTDhvRFo5dThKUUR0emJPcQpXRE9mRThHSGhteE90bVFsNllQcVJQbmM2TWRzUnEzNEg3YWNtdEErL2tTYml1MFA4UmVDZzJha2FlZWpOKy9RCnR0M2pMMWZ0WE56TDZySjhEdnNHek9hUUR0SnhqbWZmS1lmbFQyRlI1ZUwrdXhST0FaOEs2QzhmMVBuSzRWTGcKUGY3YW9BOHZVTkdpRGdYQkRNRExrWXZTRDhRbW5NTXY1K2lqa28xL3lWM1pkbkxGMHRKL0grMnVIZFV2MkliawpzUGJlRUhJMGNOc2owK0dHVDQrVWFibTRxNWhxRER0cTJsQ1VUZHRnUGpIVGRiZ2NyWlZQblNVQ0F3RUFBYU9CCm5qQ0JtekFkQmdOVkhRNEVGZ1FVdVJVdkQ3MlhuKzRHc2J6UjR3bDJmTjhTbW1Jd0h3WURWUjBqQkJnd0ZvQVUKdVJVdkQ3MlhuKzRHc2J6UjR3bDJmTjhTbW1Jd0RnWURWUjBQQVFIL0JBUURBZ1dnTUNBR0ExVWRKUUVCL3dRVwpNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBbkJnTlZIUkVFSURBZWdoeHRkWFJoZEdsdVp5MTNaV0pvCmIyOXJMbVJsWm1GMWJIUXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCUWJTVlFVVjlKV205QnY0b3MKK0l6clhubFR5WDVRdE95cUlMZ1VVRi9CeFhMaTFnbXJSNnBpZ3lXb212L1ExMzFEencyaDB1bVhWeXFQaitSUwpBelFFOE11aVE4ZzJjYTlhQ0xGUFUrLzljQnNxV0pwUkwwRXRqdWtlYWNQZkxoczNTZXF5cWRjSDJCWW1JQUd4ClMvL2hHQXRTNnVKa1FBR2xNSEYyVisyUnNpY2t5djMyd0wyQmNmSFA2eDZ2VHRNUU1YWXVVdzN2QmlUWkU3elQKS21waXlIL1hJNVc1Ry9vdmdac0o3Z3kyZnB6WmYxeVc3T0dyU1d2OCtwYW5wQW1OUGU0ZGJnMDc2Wk96ckUrZApmWjRQcHRiSmdOR3ZqTUpjaDc0NnJtNmhEU25OY09nY05GcDJicDZxNzg4eVphUlhtU1pJeTRuWjZOK3k2bW1BCk53NTEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      namespace: default
      name: mutating-webhook
      path: /mutate
      port: 5000